### ISSUE TITLE
Refactor rmw_connext into rmw_connext and rmw_dds

### ISSUE THREAD

**Issue by jwillemsen** [ros2/rmw_connext#327]
#### Feature description
For IDL to C++ based DDS implementations there is no need for making a complete rmw_ library to integrate one vendor. By using a generic rmw_dds library vendors like connext, splice, opendds can be integrated with much less code duplication. We have done this for connext and opendds as part of [AXCIOMA](http://www.axcioma.org), it took us several iterations but at the end the core differences are minimal between DDS vendors

Using some templates or helper classes the minimal changes between vendors can be handled, these changes are in the area of:
- Retrieval of the domain participant factory
- QoS XML usage

**Comment by adamsj-oci** [comment]
@jwillemsen, did you mean to call it rm_connect in the title? I'm assuming you meant rmw_connext. It probably won't make a difference but might be helpful for searching, etc to change it.

**Comment by dirk-thomas** [comment]
While this would be a good goal for a refactoring there are difference in the API of each vendor which will likely be a problem.

Also since nobody is planning to work on this and it had been about a year since this ticket was filled I will go ahead and close the ticket. Please feel free to continue commenting. Any pull request towards this goal would be appreciated.
