### ISSUE TITLE
Header files not listed in generated Visual Studio solutions

### ISSUE THREAD

**Issue by jwillemsen** [ros2/rmw_connext#338]
## Bug report

**Required Info:**

- Installation type:
  - Source
- Version or commit hash:
  - master

#### Steps to reproduce issue
After generating the Visual Studio 2017 solutions I see only Source_Files in the solution but not the Header_files section. Would be much easier for searching when the header files within the project are also in a Header_Files section in the visual studio solution

**Comment by dirk-thomas** [comment]
The CMake generators for Visual Studio and XCode only show the files which are explicitly listed in the `CMakeLists.txt` files when invoking `add_executable` / `add_library`. Since it is functionally not necessary to include header files in these places pretty much all packages only enumerate the sources files there.

That being said it should be easy to add the header files in these cases too in order to show them in Visual Studio / XCode. Please consider to contribute PRs for this.

**Comment by clalancette** [comment]
Closing, since with Foxy now being [End-of-Life](https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2023-06-20/32039), this repository is no longer used.
